title: Zhang Yichen's Homepage
page-top-title: Zhang Yichen
top-section-bg-text: Control Science and Engineering
home-subtitle: Zhang Yichen&ensp;|&ensp;张燚辰
copyright-text: '&copy; Zhang Yichen 2024-2025. All Rights Reserved.'
